### PR TITLE
Fix config resolution

### LINKED ISSUE #206: Crash at startup with token.p8 - bad_auth
I am trying to start MongoosePush ver 2.1.0 from the command line:
`_build/prod/rel/mongoose_push/bin/mongoose_push start`

It would crash with the following errors:
```
{
   "application":"mongoose_push",
   "at":"Elixir.MongoosePush.Service.APNS.Supervisor.convert_token_pool_to_sparrow/2:150",
   "erl_level":"error",
   "file":"lib/mongoose_push/service/apns/supervisor.ex",
   "key":null,
   "mode":"dev",
   "p8_file":"/home/developer/MongoosePush-master/_build/prod/rel/mongoose_push/lib/mongoose_push-2.1.0/priv/apns/token.p8",
   "pid":"#PID<0.1801.0>",
   "reason":"bad_auth",
   "result":"error",
   "severity":"error",
   "team":null,
   "text":"Required configuration missing",
   "what":"configuration",
   "when":"2022-10-02T19:02:12.722",
   "domain[0]":"elixir"
}
```

```
{
  "application": "mongoose_push",
  "at": "Elixir.MongoosePush.Service.APNS.Supervisor.convert_token_pool_to_sparrow/2:150",
  "erl_level": "error",
  "file": "lib/mongoose_push/service/apns/supervisor.ex",
  "key": null,
  "mode": "prod",
  "p8_file": "/home/developer/MongoosePush-master/_build/prod/rel/mongoose_push/lib/mongoose_push-2.1.0/priv/apns/token.p8",
  "pid": "#PID<0.1801.0>",
  "reason": "bad_auth",
  "result": "error",
  "severity": "error",
  "team": null,
  "text": "Required configuration missing",
  "what": "configuration",
  "when": "2022-10-02T19:02:12.722",
  "domain[0]": "elixir"
}
```
I have copied the files from Apple into the `/home/developer/MongoosePush-master/_build/prod/rel/mongoose_push/lib/mongoose_push-2.1.0/priv` directories.

Does anyone have  any idea or solution about these?

It says "Required configuration missing" but it doesn't seem to be using any files under the `config` directory.

Many thanks in advance.

### PR DESCRIPTION
**Pull request by pawlooss1**
This PR changes resolution of configuration environmental variables.
Previously the resolver would iterate over all configuration keys and call `Confex.fetch_env!(app, key)` to resolve all values. The issue with it was that if some keys were already set by TOML resolver they would still be seen as `{:system, type, var_name, default}` which led to overriding TOML config with defaults.
Also, it changes default values of `PUSH_*_ENABLED` to false to avoid implicit creation of an incorrect pool.
At last it fixes a clash where after defining some service pools in TOML file, entries from `prod.exs` would be appended to them due to the behaviour of `Config.Reader.merge/2`. If someone defines pools in TOML file then no other pools should be created.

### CODE REVIEW

File: lib/mongoose_push/config/provider/toml.ex [hunk 1]
```diff
@@ -49,12 +51,21 @@ defmodule MongoosePush.Config.Provider.Toml do
     |> update_service(toml_config, :apns)
   end
 
+  defp maybe_erase_confex_services(config, updated_sysconfig) do
+    # If some pools are defined in TOML config we want to remove the default ones explicitely
+    # because Config.Reader.merge/2 would keep them both and the default would still be created
```
Comment (chrzaszcz) [inline lib/mongoose_push/config/provider/toml.ex]:
```suggestion
    # If some pools are defined in TOML config, we want to remove the default ones explicitly
    # because Config.Reader.merge/2 would keep them both, and the default would still be created
```

File: lib/mongoose_push/config/provider/toml.ex [hunk 2]
```diff
@@ -17,11 +17,13 @@ defmodule MongoosePush.Config.Provider.Toml do
       current_sysconfig = Application.get_all_env(@app)
       updated_sysconfig = update_sysconfig(current_sysconfig, toml_config)
 
+      config = maybe_erase_confex_services(config, updated_sysconfig)
```
Comment (chrzaszcz) [inline lib/mongoose_push/config/provider/toml.ex:20]: How do we know that the Confex provider is applied before the TOML one?

**Review by chrzaszcz — COMMENTED** [review]
Looks good in general. I just added a question.

File: lib/mongoose_push/config/provider/toml.ex (hunk 2 above)
Comment (pawlooss1) [reply lib/mongoose_push/config/provider/toml.ex:20]: The order is defined in `mix.exs` [here](https://github.com/esl/MongoosePush/blob/master/mix.exs#L201). Actually it's the other way - TOML is applied before Confex. Here we're erasing Confex entries before they're even resolved. For instance, in [prod.exs](https://github.com/esl/MongoosePush/blob/master/config/prod.exs#L48) we have a `default` fcm pool which is composed of Confex entries in format `{:system, type, var_name, default}`. We want to ensure that this whole pool is erased if other pools are defined by TOML config. Same goes for apns.

Comment (chrzaszcz) [reply lib/mongoose_push/config/provider/toml.ex:20]: Sounds good. I knew the order from `mix.exs`, but I incorrectly assumed that we are removing the resolved pools.

**Review by chrzaszcz — APPROVED** [review]
Looks good 👍
